remote_theme: "mmistakes/minimal-mistakes"

title: "Rebecca Meyer"
email: "rlwinterisu@gmail.com"
description: "Data Analytics Portfolio"

plugins:
  - jekyll-include-cache

# Author info
author:
  name: "Rebecca Meyer"
  avatar: "/assets/images/avatar.png"
  bio: "Data Analyst | Tableau | Python | SQL"
  location: "Algonquin, IL USA"

# Site settings
markdown: kramdown
highlighter: rouge
paginate: 5

# Defaults for posts/projects
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      show_date: true
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: single
      author_profile: true
      toc: true
